### ISSUE TITLE
Problem during test

### ISSUE THREAD

**Issue by 18827513379** [Justones/ALEN#1]
I converted the pictures in my test set to raw format, but I still reported an error.

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/ALEN-master/main.py", line 201, in <module>
    main()
  File "C:/Users/Administrator/Desktop/ALEN-master/main.py", line 195, in main
    test()
  File "C:/Users/Administrator/Desktop/ALEN-master/main.py", line 177, in test
    for (step,data) in enumerate(dataLoader):
  File "D:\DeeplearingTookit\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\DeeplearingTookit\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\Administrator\Desktop\ALEN-master\dataset.py", line 130, in __getitem__
    low_im = pack_raw(rawpy.imread(self.low_names[index]))
  File "D:\DeeplearingTookit\anaconda\lib\site-packages\rawpy\__init__.py", line 20, in imread
    d.open_file(pathOrFile)
  File "rawpy\_rawpy.pyx", line 404, in rawpy._rawpy.RawPy.open_file
  File "rawpy\_rawpy.pyx", line 914, in rawpy._rawpy.RawPy.handle_error
rawpy._rawpy.LibRawFileUnsupportedError: b'Unsupported file format or not RAW file'

When reading the file, it was found that it was not read in. If possible, you can add a WeChat account, 18827513379

**Comment by Justones** [comment]
Rawpy can read most types of camera raw images, please make sure you convert them correctly

**Comment by dusthidden** [comment]
When I run the test, the code can't read the test data. It shows that the number of test samples are 0. If possible, you can add a WeChat account, 13915566855. Thanks
